import Head from 'next/head'
import Layout from "../components/layout";

export default function About() {
    return (
        <Layout>
            <Head>
                <title>About</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <section>
                <div className="font-serif py-8 px-8 mx-auto text-start md:px-20 lg:py-12 lg:px-44">
                    <h1 className="border-t-2 border-black dark:border-white pt-12 mb-8 mt-4 sm:mt-8 lg:mt-12 text-4xl font-bold tracking-tight leading-none text-gray-900 md:text-5xl lg:text-6xl dark:text-white">
                        About
                    </h1>
                </div>
            </section>
        </Layout>
    )
}
