import Head from 'next/head'
import Layout from "@/components/layout";
import ContactCard from "@/components/contactCard";
import { getContacts } from "@/pages/api/contacts";

export default function Contact({contacts}) {
    return (
        <Layout>
            <Head>
                <title>About</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <section>
                <div className="px-8 mx-auto text-start">
                    <h1 className="border-t-2 border-black dark:border-white pt-12 mb-8 mt-4 sm:mt-8 text-4xl font-bold text-gray-900 dark:text-white">
                        Contact
                    </h1>
                    <div className="flex justify-between flex-wrap">
                        {contacts.map((contact, index) => (
                            <ContactCard key={index} contact={contact}/>
                        ))}
                    </div>
                </div>
            </section>
        </Layout>
    )
}

export async function getStaticProps() {
    try {
        const contacts = await getContacts();

        return {
            props: {
                contacts: contacts.contacts,
            }
        };
    } catch (error) {
        console.error('Error:', error);
        return {
            props: {
                contacts: [],
            },
        };
    }
}
