import Head from 'next/head'
import Layout from "@/components/layout";
import ProjectCard from "@/components/projectCard";

export default function Projects() {
    let placeHolderProjects = [
        {
            title: 'Some Interesting Project',
            description: 'This is a description for the interesting project',
            slug: '/project-placeholder-1'
        },
        {
            title: 'Another Project',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed neque elit, tristique quis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed neque elit, tristique quis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed neque elit, tristique quis',
            slug: '/project-placeholder-2'
        },
        {
            title: 'Project Title',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed neque elit, tristique quis tempus',
            slug: '/project-placeholder-3'
        }
    ]

    return (
        <Layout>
            <Head>
                <title>Projects</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <section>
                <div className="px-8 mx-auto text-start">
                    <h1 className="border-t-2 border-black dark:border-white pt-12 mb-8 mt-4 sm:mt-8 text-4xl font-bold tracking-tight leading-none text-gray-900 dark:text-white">
                        Projects
                    </h1>
                    <p className="text-gray-900 dark:text-white mb-8">
                        {`Here are some of the projects I've worked on:`}
                    </p>
                    <div className="space-y-4">
                        {placeHolderProjects.map((project, index) => (
                            <ProjectCard key={index} project={project}/>
                        ))}
                    </div>
                </div>
            </section>
        </Layout>
    )
}
