import Head from 'next/head'
import Layout from "../../components/layout";
import Link from "next/link";

export default function Projects() {
    return (
        <Layout>
            <Head>
                <title>Projects</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <section>
                <div className="font-serif py-8 px-8 mx-auto text-start md:px-20 lg:py-12 lg:px-44">
                    <h1 className="border-t-2 border-black dark:border-white pt-12 mb-8 mt-4 sm:mt-8 lg:mt-12 text-4xl font-bold tracking-tight leading-none text-gray-900 md:text-5xl lg:text-6xl dark:text-white">
                        Projects
                    </h1>
                    <ul className="flex flex-col py-4 space-y-4 text-black dark:text-white">
                        <li>
                            <Link href="/">Project Placeholder 1</Link>
                        </li>
                        <li>
                            <Link href="/">Project Placeholder 2</Link>
                        </li>
                        <li>
                            <Link href="/">Project Placeholder 3</Link>
                        </li>
                    </ul>
                </div>
            </section>
        </Layout>
    )
}
